// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQxCFWanL5JMADIpE4IX1jdPcOkqTpREY',
    appId: '1:1037038130134:web:860653927e8aa0904c0a77',
    messagingSenderId: '1037038130134',
    projectId: 'habit-track-771c3',
    authDomain: 'habit-track-771c3.firebaseapp.com',
    storageBucket: 'habit-track-771c3.appspot.com',
    measurementId: 'G-0F6KGZKG9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWSyEl047TLyD7aYtYG7ylICsMij5lcWk',
    appId: '1:1037038130134:android:90c420a15cb453a24c0a77',
    messagingSenderId: '1037038130134',
    projectId: 'habit-track-771c3',
    storageBucket: 'habit-track-771c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjP4pWLUQHEdjRRQ1pMy6YDl6JL2MA8PQ',
    appId: '1:1037038130134:ios:8566f4b707ce0c404c0a77',
    messagingSenderId: '1037038130134',
    projectId: 'habit-track-771c3',
    storageBucket: 'habit-track-771c3.appspot.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjP4pWLUQHEdjRRQ1pMy6YDl6JL2MA8PQ',
    appId: '1:1037038130134:ios:8566f4b707ce0c404c0a77',
    messagingSenderId: '1037038130134',
    projectId: 'habit-track-771c3',
    storageBucket: 'habit-track-771c3.appspot.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQxCFWanL5JMADIpE4IX1jdPcOkqTpREY',
    appId: '1:1037038130134:web:d32c9cefb5c63c6a4c0a77',
    messagingSenderId: '1037038130134',
    projectId: 'habit-track-771c3',
    authDomain: 'habit-track-771c3.firebaseapp.com',
    storageBucket: 'habit-track-771c3.appspot.com',
    measurementId: 'G-6ERNTS6NK8',
  );
}
